name: Unity Build

on: 
  push:
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Test
        uses: game-ci/unity-test-runner@v2
        with:
          unityVersion: '2022.3.22f1' # Substitua pela versão do Unity que você está usando
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: '2022.3.22f1' # Substitua pela versão do Unity que você está usando
          targetPlatform: StandaloneWindows64 # Substitua pela plataforma de destino desejada
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Game Build
          path: build/
